# Generated by Django 5.1.7 on 2025-04-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug_title", models.SlugField()),
                (
                    "topics",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("technology", "Technology"),
                            ("science", "Science"),
                            ("math", "Mathematics"),
                            ("education", "Education"),
                            ("health", "Health & Wellness"),
                            ("business", "Business"),
                            ("finance", "Finance"),
                            ("sports", "Sports"),
                            ("art", "Art & Design"),
                            ("music", "Music"),
                            ("history", "History"),
                            ("literature", "Literature"),
                            ("travel", "Travel"),
                            ("food", "Food & Cooking"),
                            ("photography", "Photography"),
                            ("gaming", "Gaming"),
                            ("language", "Language Learning"),
                            ("coding", "Programming & Development"),
                            ("career", "Career Development"),
                            ("self_improvement", "Self Improvement"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Uzbek", "Uzbek"),
                            ("English", "English"),
                            ("Polish", "Polish"),
                            ("Russian", "Russian"),
                        ],
                        default="en",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=250)),
                ("date_time", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("number_of_seats", models.PositiveIntegerField()),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("UZS", "UZS"),
                            ("USD", "USD"),
                            ("PLN", "PLN"),
                            ("RUB", "RUB"),
                        ],
                        default="USD",
                        max_length=50,
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(blank=True, null=True, upload_to="images/"),
                ),
                ("description", models.TextField()),
                (
                    "guests",
                    models.ManyToManyField(
                        related_name="Guests", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Host",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
