# Generated by Django 5.1.7 on 2025-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="topics",
        ),
        migrations.AddField(
            model_name="event",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="Topics", to="events.topic"
            ),
        ),
    ]
