# Generated by Django 5.1.7 on 2025-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_topic_remove_event_topics_event_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UZS", "UZS"),
                    ("USD", "USD"),
                    ("PLN", "PLN"),
                    ("RUB", "RUB"),
                ],
                default="USD",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=6, null=True
            ),
        ),
    ]
