# Generated by Django 5.1.7 on 2025-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_currency_alter_event_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
