# Generated by Django 5.1.7 on 2025-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
