# Generated by Django 5.0.6 on 2024-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
