# Generated by Django 5.0.6 on 2024-06-25 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug_title", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug_title", models.SlugField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug_title", models.SlugField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Uzbek", "Uzbek"),
                            ("English", "English"),
                            ("Polish", "Polish"),
                            ("Russian", "Russian"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=250)),
                ("date_time", models.DateTimeField()),
                ("number_of_seats", models.PositiveIntegerField()),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("UZS", "UZS"),
                            ("USD", "USD"),
                            ("PLN", "PLN"),
                            ("RUB", "RUB"),
                        ],
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.FileField(upload_to=None)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="Guests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Host",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(blank=True, null=True, to="api.topic"),
                ),
            ],
        ),
    ]
